name: Episodes  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: /episodes get lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-g.zip episodes/get/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-g
            zip_file: m-s-episodes-g.zip
      - name: /episodes post lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-po.zip episodes/post/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-po
            zip_file: m-s-episodes-po.zip
      - name: /episodes/{episode_id} get lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-g.zip episodes/episode_id/get/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-g
            zip_file: m-s-episodes-episode-g.zip
      - name: /episodes/{episode_id} put lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-pu.zip episodes/episode_id/put/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-pu
            zip_file: m-s-episodes-episode-pu.zip
      - name: /episodes/{episode_id} delete lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-d.zip episodes/episode_id/delete/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-d
            zip_file: m-s-episodes-episode-d.zip
      - name: /episodes/{episode_id}/clips get lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-clips-g.zip episodes/episode_id/clips/get/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-clips-g
            zip_file: m-s-episodes-episode-clips-g.zip
      - name: /episodes/{episode_id}/clips post lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-clips-po.zip episodes/episode_id/clips/post/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-clips-po
            zip_file: m-s-episodes-episode-clips-po.zip
      - name: /episodes/{episode_id}/clips/{clip_id} delete lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-clips-clip-d.zip episodes/episode_id/clips/clip_id/delete/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-clips-clip-d
            zip_file: m-s-episodes-episode-clips-clip-d.zip
      - name: /episodes/{episode_id}/guests get lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-guests-g.zip episodes/episode_id/guests/get/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-guests-g
            zip_file: m-s-episodes-episode-guests-g.zip
      - name: /episodes/{episode_id}/guests post lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-guests-po.zip episodes/episode_id/guests/post/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-guests-po
            zip_file: m-s-episodes-episode-guests-po.zip
      - name: /episodes/{episode_id}/guests/{guest_id} delete lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-guests-guest-d.zip episodes/episode_id/guests/guest_id/delete/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-guests-guest-d
            zip_file: m-s-episodes-episode-guests-guest-d.zip
      - name: /episodes/{episode_id}/quotes get lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-quotes-g.zip episodes/episode_id/quotes/get/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-quotes-g
            zip_file: m-s-episodes-episode-quotes-g.zip
      - name: /episodes/{episode_id}/quotes post lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-quotes-po.zip episodes/episode_id/quotes/post/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-quotes-po
            zip_file: m-s-episodes-episode-quotes-po.zip
      - name: /episodes/{episode_id}/quotes/{quote_id} delete lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-quotes-quote-d.zip episodes/episode_id/quotes/quote_id/delete/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-quotes-quote-d
            zip_file: m-s-episodes-episode-quotes-quote-d.zip
      - name: /episodes/{episode_id}/segments get lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-segments-g.zip episodes/episode_id/segments/get/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-segments-g
            zip_file: m-s-episodes-episode-segments-g.zip
      - name: /episodes/{episode_id}/segments post lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-segments-po.zip episodes/episode_id/segments/post/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-segments-po
            zip_file: m-s-episodes-episode-segments-po.zip
      - name: /episodes/{episode_id}/segments/{segment_id} delete lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-segments-segment-d.zip episodes/episode_id/segments/segment_id/delete/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-segments-segment-d
            zip_file: m-s-episodes-episode-segments-segment-d.zip
      - name: /episodes/{episode_id}/tags get lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-tags-g.zip episodes/episode_id/tags/get/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-tags-g
            zip_file: m-s-episodes-episode-tags-g.zip
      - name: /episodes/{episode_id}/tags post lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-tags-po.zip episodes/episode_id/tags/post/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-tags-po
            zip_file: m-s-episodes-episode-tags-po.zip
      - name: /episodes/{episode_id}/tags/{tag_id} delete lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-tags-tag-d.zip episodes/episode_id/tags/tag_id/delete/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-tags-tag-d
            zip_file: m-s-episodes-episode-tags-tag-d.zip
      - name: /episodes/{episode_id}/takeaways get lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-takeaways-g.zip episodes/episode_id/takeaways/get/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-takeaways-g
            zip_file: m-s-episodes-episode-takeaways-g.zip
      - name: /episodes/{episode_id}/takeaways post lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-takeaways-po.zip episodes/episode_id/takeaways/post/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-takeaways-po
            zip_file: m-s-episodes-episode-takeaways-po.zip
      - name: /episodes/{episode_id}/takeaways/{takeaway_id} delete lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-takeaways-takeaway-d.zip episodes/episode_id/takeaways/takeaway_id/delete/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-takeaways-takeaway-d
            zip_file: m-s-episodes-episode-takeaways-takeaway-d.zip
      - name: /episodes/{episode_id}/tasks get lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-tasks-g.zip episodes/episode_id/tasks/get/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-tasks-g
            zip_file: m-s-episodes-episode-tasks-g.zip
      - name: /episodes/{episode_id}/tasks post lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-tasks-po.zip episodes/episode_id/tasks/post/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-tasks-po
            zip_file: m-s-episodes-episode-tasks-po.zip
      - name: /episodes/{episode_id}/tasks/{task_id} delete lambda deploy zip
        uses: postman-open-technologies/breaking-changes@main
        with:
            args: zip -qq -r m-s-episodes-episode-tasks-task-d.zip episodes/episode_id/tasks/task_id/delete/index.js node_modules
      - name: breaking-changes get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-episodes-episode-tasks-task-d
            zip_file: m-s-episodes-episode-tasks-task-d.zip          